### ISSUE TITLE
Improve `liblnk-python` installation documentation 

### ISSUE THREAD

**Issue by techolga** [libyal/liblnk#51]
Hi,
I tried to setup the Python bindings for a project and it took me a while to find the pip package and realize that `build-essential` is a requirement for installation (the error message is not really helpfull see below). Would be great to have this in the documentation and to have link to the github project to the [pypi page](https://pypi.org/project/liblnk-python/).

<details><summary>Error if `build-essential` is not installed</summary>
<p>
$ pip install liblnk-python

Looking in indexes: https://pypi.org/simple, https://client:****@pypi.damas.pilatus-aircraft.com/simple/
Collecting liblnk-python
  Using cached liblnk-python-20240423.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: liblnk-python
  Building wheel for liblnk-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for liblnk-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/home/airflow/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/airflow/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/airflow/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 292, in <module>
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-x_664f78/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "<string>", line 71, in run
        File "<string>", line 50, in _RunCommand
      RuntimeError: Running: sh configure --disable-nls --disable-shared-libs failed with error:
          necessary).  You can also try re-running configure with the
          '--disable-dependency-tracking' option to at least be able to build
          the package (albeit without support for automatic dependency tracking).
      See `config.log' for more details
      .
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for liblnk-python
Failed to build liblnk-python
ERROR: Could not build wheels for liblnk-python, which is required to install pyproject.toml-based projects
</p>
</details> 

Besides that, thanks for the effort you put into this library!

**Comment by joachimmetz** [comment]
Thanks for the feedback. I'll consider referencing the PyPI page from the github documentation for a later date. Regarding changes to the documentation please feel free to provide a PR on https://github.com/libyal/liblnk/wiki.  Hard to asses for me what specific information could have been beneficial for your troubleshooting.

Given that wheels are now deployed for most mainstream platforms closing this issue
